name: Create artifact

on:
  workflow_dispatch:
  push:
    paths:
      - '**.lua'
      - '**.png'
      - '**.cfg'
      - '**.ogg'
      - '**.wav'
      - '**.json'
      - '**.txt'

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read info.json
        id: mod_info
        run: |
          VERSION=$(jq -r .version ./info.json)
          NAME=$(jq -r .name ./info.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          
      - name: Make directory and copy files
        id: prepare_mod
        run: |
          ARTIFACT_DIR="${{ steps.mod_info.outputs.name }}_${{ steps.mod_info.outputs.version }}"
          MOD_DIR="${{ steps.mod_info.outputs.name }}_${{ steps.mod_info.outputs.version }}-${{ github.run_id }}"
          DEST_DIR="$HOME/$ARTIFACT_DIR/$MOD_DIR"
          mkdir -p "$DEST_DIR"
          
          SOURCE_DIR=$(dirname "./")
          cp -rv "$SOURCE_DIR"/* "$DEST_DIR"
          
          OUT_DIR="$HOME/$ARTIFACT_DIR/"
          echo "out_dir=$OUT_DIR" >> $GITHUB_OUTPUT
          echo "art_dir=$ARTIFACT_DIR" >> $GITHUB_OUTPUT
          echo "mod_dir=$MOD_DIR" >> $GITHUB_OUTPUT
      
      - name: Make artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.prepare_mod.outputs.art_dir }}"
          path: |
            ${{ steps.prepare_mod.outputs.out_dir }}
            !.gitattributes
            !.gitignore
            !.github
            !LICENSE.txt
            !README.md
